sudo: false
addons:
  apt:
    packages:
    - texlive-base
    - texlive-latex-recommended
    - texlive-extra-utils
    - texlive-fonts-recommended
    - texlive-font-utils
    - texlive-lang-french
    - texlive-latex-extra
    - texlive-math-extra
    - texlive-xetex
    - texlive-pictures
    - pgf
    - latex-xcolor
    - lmodern
    - latexmk

install:
- mkdir -p ~/.fonts
- cp java-software-engineer/fonts/* ~/.fonts/
- fc-cache -f -v

script:
- cd java-software-engineer
- latexmk
